### ISSUE TITLE
Remove a client from an fa

### ISSUE THREAD

**Issue by BurgundyBadger** [MetisSoftware/WealthManagementTool#19]
Remove a client from an fa, but keep them in the database.
Probably just a case of changing a clients fa variable to something else(Null, or the admin user)

**Comment by ben100691** [comment]
I was thinking maybe instead of buttons, we could have something like an [x] next to the clients name for quick deletion? similar to what ios do with contacts

**Comment by BurgundyBadger** [comment]
Yeah sounds like what I had in mind
