### ISSUE TITLE
Get to Client page from Meeting page

### ISSUE THREAD

**Issue by AlexDSharpe** [MetisSoftware/WealthManagementTool#33]
In the functional requirements.

**Comment by ben100691** [comment]
The user can already get to the clients page from the meeting page via clicking clients on the top bar?

**Comment by AlexDSharpe** [comment]
It was just a thing in the functional requirements, being able to go to a client's particular page from clicking their name in the Meetings page, probably to reduce the amount of clicks. If Calum (or someone else) does that thing with the meetings, where we have a populated list of clients when a meeting with a client is set up, it shouldn't be too much bother to make their name a hyperlink in meeting details, would it?

**Comment by BurgundyBadger** [comment]
You can now get to the clients page from an event
